version: '2'

services:
  worker:
    build:
      context: .
      dockerfile: Dockerfile.worker
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - SERVICE_BUS_URL=<your-service-bus>.servicebus.windows.net
      - SERVICE_BUS_NAME=<your-name>
      - SERVICE_BUS_SAK_POLICYNAME=<your-policy-name>
      - SERVICE_BUS_SAK_SHAREDSECRET=<your-shared-secret>
  web:
    build:
      context: .
      dockerfile: Dockerfile.web
    ports:
      - "5000:5000"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - SERVICE_BUS_URL=<your-service-bus>.servicebus.windows.net
      - SERVICE_BUS_NAME=<your-name>
      - SERVICE_BUS_SAK_POLICYNAME=<your-policy-name>
      - SERVICE_BUS_SAK_SHAREDSECRET=<your-shared-secret>
